# Generated by Django 2.2.16 on 2021-03-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('error', '0004_auto_20210319_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datahigieneerror',
            name='fecha',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha en que se proces√≥ el archivo'),
        ),
        migrations.AlterField(
            model_name='datahigieneerror',
            name='msg',
            field=models.CharField(max_length=255, verbose_name='Causa'),
        ),
        migrations.AlterField(
            model_name='datahigieneerror',
            name='sexo',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Sexo'),
        ),
    ]
